### ISSUE TITLE
Plugins are ignored (?)

### ISSUE THREAD

**Issue by RiseAndCry** [php-http/httplug-flex-pack#3]
Hi. Here's my config:

```
httplug:
    clients:
        test:
            http_methods_client: true
            plugins:
                - add_host:
                    host: 'test'
```

When i sendRequest (via Http\Client\Curl\Client by default) it (the request) is never modified by the plugin (i've also tried `header_defaults` plugin, to no avail). They're never called. 
The error i'm getting is from Curl Client - `url malformed`. Which makes sense as there is no host.

If i manually create a PluginClient with AddHostPlugin and pass it CurlClient, then it works fine.

So it seems that the configuration does not work. Am i missing something or did i misconfigure it ? i did read the documentation and it seems like it should just work in this case.

version: `"php-http/httplug-pack": "^1.1"`. Hope this is correct place for this question.
